name: 内核源码拉取 - Android 17 (6.18)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish-sources:
    name: "6.18.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - sub_level: "21"
            os_patch_level: "2026-06"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android17"
      kernel_version: "6.18"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
